version: 2

jobs:
  lint:
    docker:
      - image: circleci/node:10.16.2
    steps:
      - checkout
      - restore_cache:
          key: package-cache-{{checksum "package.json"}}
      - run:
          command: npm install
      - save_cache:
          key: package-cache-{{checksum "package.json"}}
          paths:
            - node_modules
      - run:
          command: npm run lint
  test:
    docker:
      - image: circleci/node:10.16.2
    steps:
      - checkout
      - restore_cache:
          key: package-cache-{{checksum "package.json"}}
      - run:
          command: npm install
      - save_cache:
          key: package-cache-{{checksum "package.json"}}
          paths:
            - node_modules
      - run:
          command: npm run test

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - lint
      - test
      - deploy:
          requires:
            - lint
            - test
          filters:
            branches:
              only: master